refactoring(spring-boot) Support older Spring Boot versions
- Add configurations to be able to generate projects for Spring Boot 1.4.7.RELEASE
- Update Travis to create projects for older Spring Boot versions
- No support for Spring Boot 1.3.x

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,24 +25,10 @@ branches:
   except:
   - test/.*
   - gh-.*
+    
 before_install:
   - echo "MAVEN_OPTS='-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m'" > ~/.mavenrc # see https://github.com/travis-ci/travis-ci/issues/4613
   - set -o pipefail
-  # start spring initializr for Ogham in background
-  - |
-    touch "$HOME/spring-initializr.log"
-    spring-initializr/./mvnw install spring-boot:run -f spring-initializr > "$HOME/spring-initializr.log" &
-    echo "$!" > "$HOME/spring-initializr.pid"
-  - grep -q 'Started SpringInitializrApplication' <(tail -f "$HOME/spring-initializr.log")
-  - cat "$HOME/spring-initializr.log"
-  # generate projects used to test the classpath on the current Ogham version
-  - OGHAM_VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
-  # TODO: it seems that parallel execution sometimes fails on Travis (seems to be spring-initializr that fails, why ?)
-  - ./mvnw spring-boot:run -pl :ogham-test-classpath -Dspring-boot.run.arguments="$HOME/classpath-tests" -Dspring-boot.run.jvmArguments="-Drunner.parallel=false -Dogham-version=$OGHAM_VERSION -Dspring.initializer.url=http://localhost:8050/starter.zip"
-  - ls -l "$HOME"
-  - ls -l "$HOME/classpath-tests"
-  # stop spring initializr
-  - kill `cat "$HOME/spring-initializr.pid"`
   # detect current Java version in order to execute classpath tests only for this version
   - |
     java_version=$(java -version 2>&1 | grep -i version | cut -d'"' -f2)
@@ -51,6 +37,34 @@ before_install:
       && echo "$java_version" | cut -d'.' -f2 > "$HOME/java-version.info" \
       || echo "$java_version" | cut -d'.' -f1 > "$HOME/java-version.info"
   - JAVA_RELEASE_VERSION=$(cat "$HOME/java-version.info")
+  # start spring initializr for Ogham in background
+  - |
+    touch "$HOME/spring-initializr.log"
+    spring-initializr/./mvnw clean spring-boot:run -f spring-initializr > "$HOME/spring-initializr.log" &
+    echo "$!" > "$HOME/spring-initializr.pid"
+    tail -f "$HOME/spring-initializr.log" &
+  - grep -q 'Started SpringInitializrApplication' <(tail -f "$HOME/spring-initializr.log")
+  - cat "$HOME/spring-initializr.log"
+  - |
+    [ "$JAVA_RELEASE_VERSION" != "8" ] && exit 0
+    touch "$HOME/spring-initializr-older-versions.log"
+    spring-initializr/./mvnw clean spring-boot:run -f spring-initializr -Dspring-boot.version=1.5.21.RELEASE -Dspring-initializr.version=0.4.0.RELEASE -Drun.jvmArguments="-Dspring.profiles.active=older-versions" > "$HOME/spring-initializr-older-versions.log" &
+    echo "$!" > "$HOME/spring-initializr-older-versions.pid"
+    tail -f "$HOME/spring-initializr-older-versions.log" &
+  - grep -q 'Started SpringInitializrApplication' <(tail -f "$HOME/spring-initializr-older-versions.log")
+  - cat "$HOME/spring-initializr-older-versions.log"
+  # generate projects used to test the classpath on the current Ogham version
+  - OGHAM_VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
+  # TODO: it seems that parallel execution sometimes fails on Travis (seems to be spring-initializr that fails, why ?)
+  - ./mvnw spring-boot:run -pl :ogham-test-classpath -Dspring-boot.run.arguments="$HOME/classpath-tests" -Dspring-boot.run.jvmArguments="-Drunner.parallel=false -Dogham-version=$OGHAM_VERSION -Dspring.initializer.url=http://localhost:8050/starter.zip"
+  - |
+    [ "$JAVA_RELEASE_VERSION" != "8" ] && exit 0
+    ./mvnw spring-boot:run -pl :ogham-test-classpath -Dspring-boot.run.arguments="$HOME/classpath-tests" -Dspring-boot.run.jvmArguments="-Drunner.parallel=false -Dogham-version=$OGHAM_VERSION -Dspring.profiles.active=older-versions -Dspring.initializer.url=http://localhost:8052/starter.zip"
+  - ls -l "$HOME"
+  - ls -l "$HOME/classpath-tests"
+  # stop spring initializr
+  - kill `cat "$HOME/spring-initializr.pid"` || echo ""
+  - kill `cat "$HOME/spring-initializr-older-versions.pid"` || echo ""
   - TEST_FOLDER=$(echo "JAVA_$JAVA_RELEASE_VERSION")
   - echo $TEST_FOLDER
   - ls -l "$HOME/classpath-tests/$TEST_FOLDER"
@@ -66,6 +80,7 @@ after_success:
 # TODO: after error -> grab logs and send it
 after_failure:
   - cat "$HOME/spring-initializr.log"
+  - cat "$HOME/spring-initializr-older-versions.log"
 notifications:
   slack:
     rooms:
@@ -78,7 +93,7 @@ notifications:
 
 cache:
   directories:
-    - $HOME/classpath-tests
+#    - $HOME/classpath-tests
     - $HOME/.m2
 before_cache:
   - rm -rf $HOME/.m2/repository/fr/sii
